Repository fluttercandies/flutter_wechat_assets_picker, pull requests merged in 2021-05, with the labels that each got.

#111 🐛 Fix Wechat Moment preview issue
  example/lib/pages/multi_assets_page.dart
  example/lib/pages/single_assets_page.dart
  lib/src/delegates/asset_picker_builder_delegate.dart
  lib/src/delegates/asset_picker_viewer_builder_delegate.dart
Labels: s: bug, ⏳TODAY

#117 🐛 pickAssets doesn't use previewThumbSize for displaying of the grid images
  README-ZH.md
  README.md
  example/lib/pages/multi_assets_page.dart
  lib/src/constants/constants.dart
  lib/src/delegates/asset_picker_builder_delegate.dart
  lib/src/delegates/asset_picker_viewer_builder_delegate.dart
  lib/src/provider/asset_entity_image_provider.dart
  lib/src/widget/asset_picker.dart
Labels: await test, e: performance

#122 ✨ Support RTL
  example/lib/main.dart
  example/lib/pages/custom_picker_page.dart
  example/lib/pages/home_page.dart
  example/lib/pages/multi_assets_page.dart
  example/lib/pages/single_assets_page.dart
  example/pubspec.yaml
  lib/src/delegates/asset_picker_builder_delegate.dart
  lib/src/delegates/asset_picker_viewer_builder_delegate.dart
  lib/src/widget/fixed_appbar.dart
Labels: s: UI, s: enhancement

#124 ⚡️ Improve image provider's constructor and decode
  example/lib/pages/multi_assets_page.dart
  example/lib/pages/single_assets_page.dart
  lib/src/delegates/asset_picker_viewer_builder_delegate.dart
  lib/src/provider/asset_entity_image_provider.dart
Labels: e: performance, r: photo_manager
